// templates/solid-start/web/src/components/billing-demo.tsx
import * as stylex from '@stylexjs/stylex'
import {
	action,
	createOptimistic,
	createSignal,
	For,
	Loading,
	Show,
	useContext,
} from 'solid-js'

import { api } from '../../../convex/_generated/api'
import { AuthContext } from '../lib/auth'
import { createConvexQuery, useConvexClient } from '../lib/convex'
import { ui } from '../styles/ui'

export function BillingDemo() {
	const auth = useContext(AuthContext)
	return (
		<article {...stylex.attrs(ui.card)}>
			<p {...stylex.attrs(ui.eyebrow)}>Stripe</p>
			<h2 {...stylex.attrs(ui.heading)}>Subscription billing</h2>
			<Show
				when={auth.user$()}
				fallback={
					<p {...stylex.attrs(ui.muted)}>
						Sign in before creating a checkout or portal session.
					</p>
				}
			>
				<Billing />
			</Show>
		</article>
	)
}

function Billing() {
	const client = useConvexClient()
	const subscriptions$ = createConvexQuery(
		api.billing.currentSubscription,
		() => ({}),
	)
	const [redirecting, setRedirecting] = createOptimistic(false)
	const [error, setError] = createSignal<string>()

	// Both sessions end in a full-page navigation to Stripe, so the flag only
	// needs to cover the round trip that mints the URL.
	const open = action(function* (kind: 'checkout' | 'portal') {
		setRedirecting(true)
		const session: { url: string | null } = yield kind === 'checkout'
			? client.action(api.billing.createSubscriptionCheckout, {})
			: client.action(api.billing.createCustomerPortal, {})
		if (!session.url) throw new Error('Stripe did not return a session URL')
		window.location.assign(session.url)
	})
	const start = (kind: 'checkout' | 'portal') => {
		setError(undefined)
		open(kind).catch((cause: Error) => setError(cause.message))
	}

	return (
		<>
			<Loading fallback={<p {...stylex.attrs(ui.muted)}>Loading billing…</p>}>
				<ul {...stylex.attrs(ui.list)}>
					<For
						each={subscriptions$()}
						keyed={(subscription) => subscription.id}
						fallback={
							<li {...stylex.attrs(ui.muted)}>
								No subscription is linked to this user.
							</li>
						}
					>
						{(subscription) => (
							<li {...stylex.attrs(ui.todo)}>
								<p>{subscription().status}</p>
								<p {...stylex.attrs(ui.muted)}>{subscription().priceId}</p>
							</li>
						)}
					</For>
				</ul>
			</Loading>
			<div {...stylex.attrs(ui.row)}>
				<button
					type="button"
					{...stylex.attrs(ui.button)}
					disabled={redirecting()}
					onClick={() => start('checkout')}
				>
					Start checkout
				</button>
				<button
					type="button"
					{...stylex.attrs(ui.button, ui.outline)}
					disabled={redirecting()}
					onClick={() => start('portal')}
				>
					Billing portal
				</button>
			</div>
			<Show when={error()}>
				{(message) => (
					<p role="alert" {...stylex.attrs(ui.error)}>
						{message()}
					</p>
				)}
			</Show>
		</>
	)
}

// templates/tanstack-start-multisite/shared/components/billing-demo.tsx
import { convexQuery } from '@convex-dev/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useConvex, useConvexAuth } from 'convex/react'

import { Button } from '@/components/ui/button'
import type { SiteId } from '@/site/site-config'
import { api } from '~/convex/_generated/api'

export function BillingDemo(props: { siteId: SiteId }) {
	const { siteId } = props
	const convex = useConvex()
	const auth = useConvexAuth()
	const subscriptions = useQuery(
		convexQuery(
			api.billing.currentSubscription,
			auth.isAuthenticated ? {} : 'skip',
		),
	)
	const checkout = useMutation({
		mutationFn: () =>
			convex.action(api.billing.createSubscriptionCheckout, { siteId }),
		onSuccess: (session) => {
			if (!session.url) {
				throw new Error('Stripe did not return a checkout URL')
			}
			window.location.assign(session.url)
		},
	})
	const portal = useMutation({
		mutationFn: () =>
			convex.action(api.billing.createCustomerPortal, { siteId }),
		onSuccess: (session) => window.location.assign(session.url),
	})

	const error = checkout.error ?? portal.error

	return (
		<article className="rounded-2xl border bg-card p-5 text-card-foreground shadow-sm">
			<p className="text-xs font-medium text-muted-foreground">Stripe</p>
			<h2 className="mt-2 text-xl font-semibold">Subscription billing</h2>
			{!auth.isAuthenticated ? (
				<p className="mt-4 text-sm text-muted-foreground">
					Sign in before creating a checkout or portal session.
				</p>
			) : (
				<>
					<div className="mt-4 space-y-2 text-sm">
						{subscriptions.data?.map((subscription) => (
							<div className="rounded-lg border p-3" key={subscription.id}>
								<p className="font-medium">{subscription.status}</p>
								<p className="truncate text-muted-foreground">
									{subscription.priceId}
								</p>
							</div>
						))}
						{subscriptions.data?.length === 0 ? (
							<p className="text-muted-foreground">
								No subscription is linked to this user.
							</p>
						) : null}
					</div>
					<div className="mt-5 flex flex-wrap gap-2">
						<Button
							disabled={checkout.isPending}
							onClick={() => checkout.mutate()}
						>
							{checkout.isPending ? 'Opening…' : 'Start checkout'}
						</Button>
						<Button
							variant="outline"
							disabled={portal.isPending}
							onClick={() => portal.mutate()}
						>
							Billing portal
						</Button>
					</div>
					{error ? (
						<p className="mt-3 text-sm text-destructive" role="alert">
							{error.message}
						</p>
					) : null}
				</>
			)}
		</article>
	)
}
