// templates/solid-start/web/src/components/todo-demo.tsx
import * as stylex from '@stylexjs/stylex'
import {
	action,
	createOptimistic,
	createSignal,
	For,
	Loading,
	Show,
	useContext,
} from 'solid-js'

import type { Id } from '../../../convex/_generated/dataModel'

import { api } from '../../../convex/_generated/api'
import { AuthContext } from '../lib/auth'
import { createConvexQuery, useConvexClient } from '../lib/convex'
import { ui } from '../styles/ui'

export function TodoDemo() {
	const auth = useContext(AuthContext)
	return (
		<article {...stylex.attrs(ui.card)}>
			<p {...stylex.attrs(ui.eyebrow)}>Convex</p>
			<h2 {...stylex.attrs(ui.heading)}>Reactive todos</h2>
			<Show
				when={auth.user$()}
				fallback={
					<p {...stylex.attrs(ui.muted)}>
						Sign in to exercise authenticated queries and mutations.
					</p>
				}
			>
				<Todos />
			</Show>
		</article>
	)
}

// Mounted only once the user is known, so the subscription starts with a token.
function Todos() {
	const client = useConvexClient()
	const todos$ = createConvexQuery(api.todos.list, () => ({}))
	const [text, setText] = createSignal('')
	const [adding, setAdding] = createOptimistic(false)
	const [error, setError] = createSignal<string>()

	// No optimistic list writes: the live query is the authority and lands the
	// confirmed row itself, so there is nothing to reconcile.
	const add = action(function* (value: string) {
		setAdding(true)
		yield client.mutation(api.todos.create, { text: value })
		setText('')
	})
	const run = (work: Promise<unknown>) => {
		setError(undefined)
		work.catch((cause: Error) => setError(cause.message))
	}
	const toggle = (id: Id<'todos'>) =>
		run(client.mutation(api.todos.toggle, { id }))
	const remove = (id: Id<'todos'>) =>
		run(client.mutation(api.todos.remove, { id }))

	return (
		<>
			<form
				{...stylex.attrs(ui.row)}
				onSubmit={(event) => {
					event.preventDefault()
					if (text().trim()) run(add(text()))
				}}
			>
				<input
					{...stylex.attrs(ui.input, ui.grow)}
					aria-label="New todo"
					placeholder="Ship something useful"
					value={text()}
					onInput={(event) => setText(event.currentTarget.value)}
				/>
				<button type="submit" {...stylex.attrs(ui.button)} disabled={adding()}>
					Add
				</button>
			</form>
			<Loading fallback={<p {...stylex.attrs(ui.muted)}>Loading todos…</p>}>
				<ul {...stylex.attrs(ui.list)}>
					{/* Every snapshot carries fresh objects; key by id so rows survive updates. */}
					<For
						each={todos$()}
						keyed={(todo) => todo._id}
						fallback={<li {...stylex.attrs(ui.muted)}>No todos yet.</li>}
					>
						{(todo) => (
							<li {...stylex.attrs(ui.row, ui.todo)}>
								<button
									type="button"
									{...stylex.attrs(ui.plain, todo().completed && ui.done)}
									onClick={() => toggle(todo()._id)}
								>
									{todo().text}
								</button>
								<button
									type="button"
									{...stylex.attrs(ui.button, ui.ghost)}
									onClick={() => remove(todo()._id)}
								>
									Remove
								</button>
							</li>
						)}
					</For>
				</ul>
			</Loading>
			<Show when={error()}>
				{(message) => (
					<p role="alert" {...stylex.attrs(ui.error)}>
						{message()}
					</p>
				)}
			</Show>
		</>
	)
}

// templates/tanstack-start-multisite/shared/components/todo-demo.tsx
import { convexQuery } from '@convex-dev/react-query'
import { useMutation, useQuery } from '@tanstack/react-query'
import { useConvex, useConvexAuth } from 'convex/react'
import { useState } from 'react'

import { Button } from '@/components/ui/button'
import { api } from '~/convex/_generated/api'

export function TodoDemo() {
	const convex = useConvex()
	const auth = useConvexAuth()
	const [text, setText] = useState('')
	const todos = useQuery(
		convexQuery(api.todos.list, auth.isAuthenticated ? {} : 'skip'),
	)

	const createTodo = useMutation({
		mutationFn: (todoText: string) =>
			convex.mutation(api.todos.create, { text: todoText }),
		onSuccess: () => setText(''),
	})
	const toggleTodo = useMutation({
		mutationFn: (id: (typeof api.todos.toggle)['_args']['id']) =>
			convex.mutation(api.todos.toggle, { id }),
	})
	const removeTodo = useMutation({
		mutationFn: (id: (typeof api.todos.remove)['_args']['id']) =>
			convex.mutation(api.todos.remove, { id }),
	})

	return (
		<article className="rounded-2xl border bg-card p-5 text-card-foreground shadow-sm">
			<p className="text-xs font-medium text-muted-foreground">Convex</p>
			<h2 className="mt-2 text-xl font-semibold">Reactive todos</h2>
			{auth.isLoading ? (
				<p className="mt-4 text-sm text-muted-foreground">
					Checking the session…
				</p>
			) : !auth.isAuthenticated ? (
				<p className="mt-4 text-sm text-muted-foreground">
					Sign in to exercise authenticated queries and mutations.
				</p>
			) : (
				<>
					<form
						className="mt-5 flex gap-2"
						onSubmit={(event) => {
							event.preventDefault()
							if (text.trim()) {
								createTodo.mutate(text)
							}
						}}
					>
						<input
							className="h-9 min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
							aria-label="New todo"
							placeholder="Ship something useful"
							value={text}
							onChange={(event) => setText(event.currentTarget.value)}
						/>
						<Button disabled={createTodo.isPending}>Add</Button>
					</form>
					<ul className="mt-4 space-y-2">
						{todos.data?.map((todo) => (
							<li
								className="flex items-center gap-2 rounded-lg border p-2"
								key={todo._id}
							>
								<button
									className="min-w-0 flex-1 text-left text-sm"
									type="button"
									onClick={() => toggleTodo.mutate(todo._id)}
								>
									<span
										className={
											todo.completed
												? 'text-muted-foreground line-through'
												: undefined
										}
									>
										{todo.text}
									</span>
								</button>
								<Button
									size="xs"
									variant="ghost"
									onClick={() => removeTodo.mutate(todo._id)}
								>
									Remove
								</Button>
							</li>
						))}
					</ul>
					{todos.data?.length === 0 ? (
						<p className="mt-4 text-sm text-muted-foreground">No todos yet.</p>
					) : null}
				</>
			)}
		</article>
	)
}
